"""Add question_type and time_limit

Revision ID: 060dc526d7c1
Revises: f9362cf41c9a
Create Date: 2026-07-06 05:05:35.803507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060dc526d7c1'
down_revision: Union[str, None] = 'f9362cf41c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('question_type', sa.String(length=50), server_default='conceptual', nullable=False))
    op.add_column('question_bank', sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_bank', 'time_limit_seconds')
    op.drop_column('question_bank', 'question_type')
    # ### end Alembic commands ###
