"""Add violation tracking to InterviewSession

Revision ID: 7970bc0abda2
Revises: 835ec67ee2e2
Create Date: 2026-07-06 05:29:15.971377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7970bc0abda2'
down_revision: Union[str, None] = '835ec67ee2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('violation_count', sa.Integer(), nullable=True))
    op.add_column('interview_sessions', sa.Column('terminated_for_violation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'terminated_for_violation')
    op.drop_column('interview_sessions', 'violation_count')
    # ### end Alembic commands ###
