"""Add consistency_feedback to reports

Revision ID: 835ec67ee2e2
Revises: 060dc526d7c1
Create Date: 2026-07-06 05:07:22.450309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835ec67ee2e2'
down_revision: Union[str, None] = '060dc526d7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('consistency_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'consistency_feedback')
    # ### end Alembic commands ###
