"""Add job_description

Revision ID: f9362cf41c9a
Revises: add_question_id_index
Create Date: 2026-07-06 05:01:01.309192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9362cf41c9a'
down_revision: Union[str, None] = 'add_question_id_index'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_messages_question_id'), table_name='interview_messages')
    op.add_column('interview_sessions', sa.Column('job_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'job_description')
    op.create_index(op.f('ix_interview_messages_question_id'), 'interview_messages', ['question_id'], unique=False)
    # ### end Alembic commands ###
