"""Add ATS fields to Resume

Revision ID: fb59bbd540ff
Revises: 7970bc0abda2
Create Date: 2026-07-06 05:31:01.581157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb59bbd540ff'
down_revision: Union[str, None] = '7970bc0abda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('ats_breakdown', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('ats_suggestions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'ats_suggestions')
    op.drop_column('resumes', 'ats_breakdown')
    op.drop_column('resumes', 'ats_score')
    # ### end Alembic commands ###
